config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
  resources :tasks, only: [:create, :show, :edit, :update, :destroy]
  
  #resources :messagesは下記の意
  # CRUD
  #get 'messages/:id', to: 'messages#show'
  #post 'messages', to: 'messages#create'
  #put 'messages/:id', to: 'messages#update'
  #delete 'messages/:id', to: 'messages#destroy'

  # index: show の補助ページ
  #get 'messages', to: 'messages#index'

  # new: 新規作成用のフォームページ
  #get 'messages/new', to: 'messages#new'

  # edit: 更新用のフォームページ
  #get 'messages/:id/edit', to: 'messages#edit'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    
    validates :content, presence: true, length: { maximum:10 }
    validates :status, presence: true, length: { maximum:10 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

  def counts(user)
    @count_tasks = user.tasks.count
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      #ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :set_task, only:[:show, :edit, :update ] 
  
  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = 'タスクを登録しました。'
      redirect_to root_url
    else
      @mtasks = current_user.tasks.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'タスクの登録に失敗しました。'
      render 'toppages/index'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'タスクは正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = 'タスクを削除しました。'
    redirect_to root_url
  end
  
  private

  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
  def set_task
    @task = Task.find(params[:id])
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :require_user_logged_in

  def index
    if logged_in?
      @task = current_user.tasks.build  # form_with 用
      @tasks = current_user.tasks.order(id: :desc).page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
  <div><%= task %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Tasklists</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto"></ul>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
           <li class="nav-item"><%= link_to 'Signup', signup_path, class:'nav-link' %></li>
           <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tasklists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_tasks' %>
      <%= yield %>

    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |f| %>

<%# エラー内容確認 %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/tasks/_tasks.html.erb
<% if @tasks.present? %>
<ul class="list-unstyled">
  <div>User: <%= current_user.name %></div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>Status</th>
        <th>Content</th>
        <th>Created_at</th>
      </tr>
    </thead>

    <% @tasks.each do |task| %>
      <tbody>
        <tr>
          <td><%= link_to task.id, task %></td>
          <td><%= task.status %></td>
          <td><%= task.content %></td>
          <td><%= task.created_at %></td>
        </tr>
      </tbody>
    <% end %>
  <%= paginate tasks %>
</ul>
<% end %>  

app/views/tasks/edit.html.erb
<div>
  <h3>id: <%= @task.id %> のタスク編集ページ</h3>
</div>
<div class="col-sm-4">
  <%= form_with(model: @task, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="form-group">
      <%= f.label :status, 'Status：' %>
      <%= f.select :status, [["Working", "Working"], ["Done", "Done"], ["Pending", "Pending"]],{} , {class: 'form-control'} %>
    </div>
    <div class="form-group">
      <%= f.label :content, 'Content：' %>
      <%= f.text_area :content, class: 'form-control', rows: 1 %>
    </div>
    <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
  <% end %>
</div>
<div>
  <%= link_to '一覧に戻る', root_url %>
</div>

app/views/tasks/old/_form.html.erb
<%= form_with(model: @task, local: true) do |f| %>

<%# エラー内容確認 %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/tasks/old/edit.html.erb
<h1>id: <%= @task.id %> の編集ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', task_path %>

app/views/tasks/old/index.html.erb
<h1>タスク一覧</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.id, task %> &lt<%= task.status %>&gt : <%= task.content %> </li>
  <% end %>
</ul>
  
  <%= paginate @tasks %>

  <%= link_to '新規タスク追加', new_task_path %>

app/views/tasks/old/new.html.erb
<h1>タスク新規作成</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/old/show.html.erb
<h1><%= @task.id %>の詳細ページ</h1>

<p>ステータス: <%= @task.status %></p>
<p>タスク: <%= @task.content %></p>

<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このタスクを編集する', edit_task_path(@task) %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/tasks/show.html.erb
<div class="row">
  <h3>id: <%= @task.id %> のタスク詳細ページ</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>id</th>
          <th>Status</th>
          <th>Content</th>
          <th>Created_at</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>

        <tbody>
          <tr>
            <td><%= @task.id %></td>
            <td><%= @task.status %></td>
            <td><%= @task.content %></td>
            <td><%= @task.created_at %></td>
            <td>
              <% if current_user == @task.user %>
                <%= link_to "Edit", edit_task_path(@task), class: 'btn btn-success btn-sm' %>
              <% end %>
            </td>
            <td>
              <% if current_user == @task.user %>
                <%= link_to "Delete", @task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
              <% end %>
            </td>
          </tr>
        </tbody>
    </table>
  </div>
  <%= link_to '一覧に戻る', root_url %>
</div>

app/views/toppages/index.html.erb
<div class="row">
  <aside class="col-sm-4">
    <%= form_with(model: @task, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :status, 'Status：' %>
        <%= f.select :status, [["Working", "Working"], ["Done", "Done"], ["Pending", "Pending"]],{} , {class: 'form-control'} %>
      </div>
      <div class="form-group">
        <%= f.label :content, 'Content：' %>
        <%= f.text_area :content, class: 'form-control', rows: 1 %>
      </div>
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </aside>
  <div class="col-sm-8">
    <%= render 'tasks/tasks', tasks: @tasks %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/old/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <div>
        <%= user.name %>
      </div>
      <div>
        <p><%= link_to 'View profile', user_path(user) %></p>
      </div>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/old/index.html.erb
<%= render 'users', users: @users %>

app/views/users/old/show.html.erb
<div class="row">
  <aside class="col-sm-4">
        <h3><%= @user.name %></h3>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Tasks<span class="badge badge-secondary"><%= @count_tasks %></span></a></li>
    </ul>
    <%= render 'tasks/tasks', tasks: @tasks %>
  </div>
</div>